django_movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("contact/", include('contact.urls')),
    path('', include('movies.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path("filter/", views.FilterMoviesView.as_view(), name = 'filter'),
    path("search/", views.Search.as_view(), name = 'search'),
    path("last/", views.MovieLast.as_view(), name = 'last'),
    path("most_popular/", views.MoviePopularView.as_view(), name = 'most_popular'),
    path('home/', views.HomeView.as_view(), name = 'home'),
    path('data-json/', views.PictureView.as_view(), name = 'data-json'),
    path("add-views/", views.MostPopular.as_view(), name='add_views'),
    # path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),
    path("json-filter/", views.JsonFilterMoviesView.as_view(), name='json_filter'),
    path('', views.MoviesView.as_view(), name = 'movie_list'),
    path('<slug:slug>/', views.MovieDetailView.as_view(), name = 'movie_detail'),
    path('review/<int:pk>/', views.AddReview.as_view(), name = 'add_review'),
    path('actor/<str:slug>/', views.ActorView.as_view(), name = 'actor_detail'),
    
]

movies/models.py
from django.db import models
from django.urls import reverse
from datetime import date

from django.db.models.expressions import Value


class Category(models.Model):
    name = models.CharField("Категорія", max_length=150)
    description = models.TextField("Опис")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категорія"
        verbose_name_plural = "Категорії"


class Actor(models.Model):
    name = models.CharField("Ім'я", max_length=100)
    age = models.PositiveSmallIntegerField("Вік", default=0)
    description = models.TextField("Опис")
    image = models.ImageField("Зображення", upload_to = "actors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs = {"slug": self.name})

    class Meta:
        verbose_name = "Актори і режисери"
        verbose_name_plural = "Актори і режисери"

    
class Genre(models.Model):
    name = models.CharField("Ім'я", max_length=100)
    description = models.TextField("Опис")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанри"


class Movie(models.Model):
    title = models.CharField("Назва", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Опис")
    poster = models.ImageField("Постер", upload_to = 'movies/')
    year = models.PositiveSmallIntegerField("Дата виходу", default=2019)
    country = models.CharField("Країна", max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name = "режисери", related_name = "film_director")
    actors = models.ManyToManyField(Actor, verbose_name = "актори", related_name = "film_actor")
    genres = models.ManyToManyField(Genre, verbose_name = "жанри")
    world_premiere = models.DateField("Прем'єра в світі", default = date.today)
    budget = models.PositiveBigIntegerField("Бюджет", default = 0, help_text = "вказувати суму в доларах")
    fees_in_usa = models.PositiveBigIntegerField(
        "Збори в США", default = 0, help_text = "вказувати суму в доларах"
    )
    fees_in_world = models.PositiveBigIntegerField(
        "Збори в світі", default = 0, help_text = "вказувати суму в доларах"
    )
    category = models.ForeignKey(Category, verbose_name = "Категорія", on_delete = models.SET_NULL, null = True)
    url = models.SlugField(max_length=130, unique=True)
    draft = models.BooleanField("Чорновик", default = False)    
    views = models.IntegerField('Перегляди', default=0, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs = {"slug": self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull = True)

    

    class Meta:
        verbose_name = "Фільм"
        verbose_name_plural = "Фільми"



class MovieShots(models.Model):
    title = models.CharField("Заголовок", max_length = 100)
    description = models.TextField("Опис")
    image = models.ImageField("Зображення", upload_to = "movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name = "Фільм", on_delete = models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр із фільму"
        verbose_name_plural = "Кадри із фільму"


class RatingStar(models.Model):
    value = models.SmallIntegerField("Значення", default = 0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Зірка рейтингу"
        verbose_name_plural = "Зірки рейтингу"
        ordering = ["-value"]


class Rating(models.Model):
    ip = models.CharField("IP - адреса", max_length = 15)
    star = models.ForeignKey(RatingStar, on_delete = models.CASCADE, verbose_name = "зірка", related_name = "ratings")
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE, verbose_name = "фільм")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    email = models.EmailField()
    name = models.CharField("ім'я", max_length = 100)
    text = models.TextField("Повідомлення", max_length = 5000)
    parent = models.ForeignKey('self', verbose_name = "Родич", on_delete = models.SET_NULL, blank = True, null = True)
    movie = models.ForeignKey(Movie, verbose_name = "фільм", on_delete = models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Відгук"
        verbose_name_plural = "Відгуки"

movies/forms.py
from django import forms
from django.forms import fields

from movies import views

from .models import Reviews, Rating, RatingStar, Movie

class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = Reviews
        fields = ("name", "email", "text")

class RatingForm(forms.ModelForm):

    star = forms.ModelChoiceField(
        queryset = RatingStar.objects.all(), widget = forms.RadioSelect(), empty_label = None
    )

    class Meta:
        model = Rating
        fields = ('star',)

class PopularForm(forms.ModelForm):

  
    class Meta:
        model = Movie
        fields = ('views',)

movies/views.py
from datetime import timedelta
from operator import mod
from re import template
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect
from django.db.models import Count
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView, View
from django.db.models import Sum
from django.utils import timezone

from .models import  Movie, Category, Actor, Genre, Rating, Reviews
from .forms import  ReviewForm, RatingForm, PopularForm




from django.shortcuts import render, redirect,get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# from .models import StudentApplying
from django.contrib.auth.models import User
from django.db.models import F

from movies import models




class GenreYear:
    """Жанри та роки виходу фільмів"""

    def get_genres(self):
        return Genre.objects.all()
    
    def get_titles(self):
        return Movie.objects.order_by("-title").values("title").distinct()

    def get_years(self):
        return Movie.objects.order_by("-year").values("year").distinct()[:]

    def get_categories(self):
        return Category.objects.all()


import random
class MoviesView(GenreYear, ListView):
    """Список фільмів"""
    model = Movie
    queryset = Movie.objects.order_by('?')
    paginate_by = 9


class MovieLast(GenreYear, ListView):
    model = Movie
    queryset = Movie.objects.order_by("-year")[:6]
    paginate_by = 6

class MoviePopularView(GenreYear, ListView):
    model = Movie
    queryset = Movie.objects.order_by("-views")[:6]
    paginate_by = 6

# class MoviePopular(GenreYear, ListView):
#     model = Movie
#     queryset = Movie.objects.order_by("-views")
#     # template_name = 'movies/most_popular.html'
#     paginate_by = 4
#     def get_queryset(self):
#         queryset = Movie.objects.filter().update(views='views' + 1)
#         return queryset

    # Movie.objects.filter(pk=model.pk).update(views=('views') + 1)


class MovieDetailView(GenreYear, DetailView):
    """Повний опис фільму"""
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    slug_field = "url"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["star_form"] = RatingForm()
        
        
        return context


class AddReview(View):
    """Відгуки"""

    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())


class ActorView(GenreYear, DetailView):
    """Виведення інформації про актора"""
    model = Actor
    template_name = 'movies/actor.html'
    slug_field = "name"


class FilterMoviesView(GenreYear, ListView):
    """Фільтр фільмів"""
    paginate_by = 6

    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre"))|
            Q(category_id__in=self.request.GET.getlist("category")) 
        ).distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["year"] = ''.join([f"year={x}&" for x in self.request.GET.getlist("year")])
        context["genre"] = ''.join([f"genre={x}&" for x in self.request.GET.getlist("genre")])
        context["category"] = ''.join([f"category={x}&" for x in self.request.GET.getlist("category")])
       
        return context


class JsonFilterMoviesView(ListView):
    """Фільтр фільмів в json"""

    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre"))
        ).distinct().values("title", "tagline", "url", "poster")
        return queryset

    def get(self, request, *args, **kwargs):
        queryset = list(self.get_queryset())
        return JsonResponse({"movies": queryset}, safe=False)


class AddStarRating(View):
    """Додавання рейтингу фільму"""

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)

class Search(GenreYear, ListView):

    paginate_by = 2

    def get_queryset(self):
        return Movie.objects.filter(title__icontains = self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'
        return context

from django.db.models import Count, F
from django.http import HttpResponse, HttpResponseRedirect

class MostPopular(GenreYear, ListView):
    # def applyStatus(request):
    #     if "applybtn" in request.POST:
    #         profil = Movie.objects.all().update(
    #             views = F('views')+1
    #         )
            
    #         # profil.save(update_fields=["applied"])
    #         return redirect('movie_list')
    #     return HttpResponse('Not done')
    def post(self, request, pk=None):
        
        if "applybtn" in request.POST:
            profil = Movie.objects.filter(title=self.request.POST.get('applybtn')).update(
                views = F('views')+1
            )
            print(request.GET.get('applybtn'))
            res = 1
            return redirect('movie_list')
        return HttpResponse('Not done')

from django.core import serializers
from django.http import JsonResponse

class HomeView(TemplateView):
    template_name = 'movies/home.html'

class PictureView(View):
    def get(self, request):
        qs = Movie.objects.all()
        data = serializers.serialize('json', qs)
        return JsonResponse({'data': data}, safe=False)

templates/movies/actor.html
{% extends 'movies/base.html' %}
{% load static %}
{% block title %} {{ actor.name }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ actor.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li>
                        <span><b>Вік:</b> {{ actor.age }} років</span></li>
                    <li>
                        <span><b>Режисер:</b>
                            {% for movie in actor.film_director.all %}
                                {{ movie.title }}
                            {% endfor %}
                        </span>
                    </li>
                    <li><span><b>Актор:</b>
                        {% for movie in actor.film_actor.all %}
                            {{ movie.title }}
                        {% endfor %}
                    </span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent">
                Про {{ actor.name }}
            </h3>
            <p class="editContent">
                {{ actor.description|safe }}
            </p>
        </div>
    </div>

    
    
{% endblock movie %}

templates/movies/base.html
{% extends 'base.html' %}
{% block content %}
<section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
    {% block container %}
        <div class="container-fluid py-md-3">
    {% endblock container %}
        <div class="row">
            {% block sidebar %}
            <div class="side-bar col-lg-3">
            {% endblock sidebar %}
            {% include 'include/sidebar.html' %}
            </div>
            {% block movie %}

                

            {% endblock movie %}

        </div>
    </div>
</section>
{% endblock content %}

templates/movies/home.html
{% extends 'base.html' %}


{% block content %}


  

    <!-- Modal -->
    <div class="modal fade" id="previewPicModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-body">
              <input type="checkbox" class="checked">
              <span>wtf</span>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
        </div>
    </div>

    <div class="text-center">
        <div class="spinner-border" role="status" id="spinner"></div>
    </div>

    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Year</th>
          </tr>
        </thead>
        <tbody id="table-body-box">
        </tbody>
      </table>

      

{% endblock content %}

templates/movies/last.html
{% extends 'movies/base.html' %}
{% block title %} {% endblock title %}
{% block header %} bg1 {% endblock header %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in last %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}"
                                   class="editContent">
                                    {{ movie.title }}
                                </a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent">{{ movie.tagline }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="grid-img-right mt-4 text-right bg bg1" >
            {% include 'include/pagination.html' %}
        </div>
    </div>
{% endblock movie %}

templates/movies/most_popular.html
{% extends 'movies/base.html' %}
{% block title %} {% endblock title %}
{% block header %} bg1 {% endblock header %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in most_popular %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}"
                                   class="editContent">
                                    {{ movie.title }}
                                </a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent">{{ movie.tagline }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="grid-img-right mt-4 text-right bg bg1" >
            {% include 'include/pagination.html' %}
        </div>
    </div>
{% endblock movie %}

templates/movies/movie_detail.html
{% extends 'movies/base.html' %}
{% load static %}
{% block title %} {{ movie.title }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}


    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li>
                        <span><b>Рік:</b> {{ movie.year }}</span></li>
                    <li>
                        <span><b>Країна:</b> {{ movie.country }}</span>
                    </li>
                    <li>
                        <span><b>Слоган:</b> {{ movie.tagline }}</span>
                    </li>
                    <li>
                        <span><b>Режисер:</b>
                            {% for director in movie.directors.all %}
                                <a href="{{ director.get_absolute_url }}">
                                    {{ director.name }},
                                </a>
                            {% endfor %}
                        </span>
                    </li>
                    <li><span><b>Актори:</b>
                        {% for actor in movie.actors.all %}
                            <a href="{{ actor.get_absolute_url }}">
                                    {{ actor.name }},
                            </a>
                        {% endfor %}
                                </span>
                    </li>
                    <!-- style="list-style: none" -->
                    <li><span><b>Жанр:</b> 
                        {% for genre in movie.genres.all %}
                            {{ genre.name }},
                        {% endfor %}
                                    </span>
                    </li>
                    <li>
                        <span><b>Прем'єра у світі:</b> {{ movie.world_premiere }}</span>
                    </li>
                    <li>
                        <span><b>Бюджет:</b> ${{ movie.budget }}</span></li>
                    <li>
                        <span><b>Збори в США:</b> ${{ movie.fees_in_usa }}</span></li>
                    <li>
                        <span><b>Збори у світі:</b> ${{ movie.fees_in_world }}</span>
                    </li>
                    <li>
                        <span><b>Ваша оцінка:</b> 
                            {% for rating in movie.rating_set.all %}
                                {{ rating.star}}
                            {% endfor %}
                
                        </span>
                    </li>
                   
                    <li>
                        <form action="{% url 'add_rating' %}" method="post" name="rating">
                            <b>Рейтинг:</b>
                            {% csrf_token %}
                            <input type="hidden" value="{{ movie.id }}" name="movie">
                            <span class="rating">
                                {% for k, v in star_form.fields.star.choices %}
                                    <input id="rating{{ v }}" type="radio" name="star"
                                           value="{{ k }}">
                                    <label for="rating{{ v }}">{{ k }}</label>
                                {% endfor %}
                            </span>
                            <span class="editContent">5.0</span>
                            
                        </form>
                    </li>
                    
                </ul>
                


                <!-- <div class="share-desc">
                    <div class="share">
                        <h4 class="editContent">
                            Share:</h4>
                        <ul class="w3layouts_social_list list-unstyled">
                            <li>
                                <a href="#" class="w3pvt_facebook editContent">
                                    <span class="fa fa-facebook-f"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_twitter editContent">
                                    <span class="fa fa-twitter"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_facebook editContent">
                                    <span class="fa fa-vk"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div> -->
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            
            <h3 class="shop-sing editContent">
                Про фільм {{ movie.title }}
            </h3>
            <p>
        
                {% for image in movie.movieshots_set.all %}
                    
                        <img src="{{ image.image.url }}" class="img-movie-shots "
                         alt="{{ image.description }}">
                    
                {% endfor %}
                
            </p>
            <p class="editContent">
                {{ movie.description|safe }}
            </p>
        </div>
        <hr>
        <div class="row">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">
                    <h3 class="editContent">
                        <span class="sub-tittle editContent">{{ movie.reviews_set.count }}</span>Залишити відгук</h3>
                    <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4"
                          id="formReview">
                        {% csrf_token %}
                        <input type="hidden" name="parent" id="contactparent" value="">
                        <div class="form-group editContent">
                            <label for="contactcomment" class="editContent">
                                Ваш коментар *
                            </label>
                            <textarea class="form-control border" rows="5" name="text"
                                      id="contactcomment" required=""></textarea>
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent">
                                <label for="contactusername" class="editContent">
                                    Ім'я *
                                </label>
                                <input type="text" class="form-control border" name="name"
                                       id="contactusername" required="">
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent">
                                <label for="contactemail" class="editContent">
                                    Email *
                                </label>
                                <input type="email" class="form-control border" name="email"
                                       id="contactemail" required="">
                            </div>
                        </div>
                        <button type="submit"
                                class="mt-3 btn btn-success btn-block py-3">
                            Відправити
                        </button>
                    </form>
                </div>
                <!--  //contact form grid ends here -->
            </div>
        </div>
        {% for review in movie.get_review %}
            <div class="media py-5">
                <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid-review" alt="image">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">
                        {{ review.name }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                    <a href="#formReview"
                       onclick="addReview('{{ review.name }}', '{{ review.id }}')">Відповісти</a>
                    {% for rew in review.reviews_set.all %}
                        <div class="media mt-5 editContent">
                            <a class="pr-3" href="#">
                                <img src="{% static 'images/te2.jpg' %}" class="img-fluid-review"
                                     alt="image">
                            </a>
                            <div class="media-body">
                                <h5 class="mt-0 editContent">{{ rew.name }}</h5>
                                <p class="mt-2 editContent">{{ rew.text }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
    <script>
        function addReview(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = `${name}, `
        }

    </script>
    
{% endblock movie %}